# Generated by Django 2.0.13 on 2019-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('detalle', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
