# Generated by Django 2.2.1 on 2019-05-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
